---
# Source: CUE apiObjects.HTTPRoute.argocd
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: istio-ingress
  labels:
    app: argocd
spec:
  hostnames:
    - argocd.holos.localhost
  parentRefs:
    - name: default
      namespace: istio-ingress
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-server
          namespace: argocd
          port: 80
---
# Source: CUE apiObjects.HTTPRoute.bank
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bank
  namespace: istio-ingress
  labels:
    app: bank
spec:
  hostnames:
    - bank.holos.localhost
  parentRefs:
    - name: default
      namespace: istio-ingress
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          namespace: bank-frontend
          port: 80
