apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: ./deploy/clusters/workload/components/external-secrets
    repoURL: https://github.com/hanssenkai/bank-of-holos
    targetRevision: main
