---
# Source: CUE apiObjects.AppProject.platform
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Holos managed AppProject
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
