apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    holos.run/component.name: stage-podinfo
  name: stage-podinfo
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/v1alpha4/deploy/clusters/local/components/stage-podinfo
    repoURL: https://github.com/holos-run/bank-of-holos
    targetRevision: main
