---
# Source: CUE apiObjects.ConfigMap.demo-data-config
metadata:
  name: demo-data-config
  namespace: bank-backend
  labels:
    application: bank-of-holos
    environment: development
    tier: backend
data:
  USE_DEMO_DATA: "True"
  DEMO_LOGIN_USERNAME: testuser
  DEMO_LOGIN_PASSWORD: bankofanthos
kind: ConfigMap
apiVersion: v1
---
# Source: CUE apiObjects.ConfigMap.environment-config
metadata:
  name: environment-config
  namespace: bank-backend
  labels:
    application: bank-of-holos
    environment: development
    tier: backend
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: /tmp/.ssh/publickey
kind: ConfigMap
apiVersion: v1
---
# Source: CUE apiObjects.ConfigMap.service-api-config
metadata:
  name: service-api-config
  namespace: bank-backend
  labels:
    application: bank-of-holos
    environment: development
    tier: backend
data:
  TRANSACTIONS_API_ADDR: ledgerwriterbank-backend.svc:8080
  BALANCES_API_ADDR: balancereaderbank-backend.svc:8080
  HISTORY_API_ADDR: transactionhistory.bank-backend.svc:8080
  CONTACTS_API_ADDR: contacts.bank-backend.svc:8080
  USERSERVICE_API_ADDR: userservice.bank-backend.svc:8080
kind: ConfigMap
apiVersion: v1
---
# Source: CUE apiObjects.ExternalSecret.jwt-key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-key
  namespace: bank-backend
  labels:
    application: bank-of-holos
    environment: development
    tier: backend
spec:
  dataFrom:
    - extract:
        key: jwt-key
  refreshInterval: 5s
  secretStoreRef:
    kind: SecretStore
    name: bank-security
  target:
    name: jwt-key
---
# Source: CUE apiObjects.ReferenceGrant.grant
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: istio-ingress
  namespace: bank-backend
  labels:
    application: bank-of-holos
    environment: development
    tier: backend
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: istio-ingress
  to:
    - group: ""
      kind: Service
---
# Source: CUE apiObjects.SecretStore.bank-of-holos
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: bank-security
  namespace: bank-backend
  labels:
    application: bank-of-holos
    environment: development
    tier: backend
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: bank-of-holos
      remoteNamespace: bank-security
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
        url: https://kubernetes.default.svc
---
# Source: CUE apiObjects.ServiceAccount.bank-of-holos
metadata:
  name: bank-of-holos
  namespace: bank-backend
  labels:
    application: bank-of-holos
    environment: development
    tier: backend
kind: ServiceAccount
apiVersion: v1
